FROM openjdk:8
EXPOSE 8282
ADD build/libs/employee-management-project-0.0.1-SNAPSHOT.jar  employee-management-project-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","/employee-management-project-0.0.1-SNAPSHOT.jar" ]